version: '3'

services:
    mypostgres:
        image: postgres
        environment:
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: dev
            POSTGRES_DB: react
        ports:
            - '5432:5432'
        networks:
            - mynetwork
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    backend:
        build:
            context: ./server
        ports:
            - '3000:3000'
        networks:
            - mynetwork
        depends_on:
            - mypostgres

    frontend:
        build:
            context: ./client
        ports:
            - '5173:5173'
        networks:
            - mynetwork
        depends_on:
            - backend

networks:
    mynetwork:
